# docker configuration for running a development server
version: "3.6"

services:
  job-server:
    build: .
    environment:
      - ADMIN_USERS
      - DATABASE_URL
      - DEBUG
      - GITHUB_OPENSAFELY_TOKEN
      - SECRET_KEY=${SECRET_KEY:-12345}
      - SOCIAL_AUTH_GITHUB_KEY
      - SOCIAL_AUTH_GITHUB_SECRET
    ports:
      - "8000:8000"
    command: /app/manage.py runserver 0.0.0.0:8000
